apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ai-operator-servicemonitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  namespaceSelector:
    matchNames:
      - ai-inference-orchestrator-system
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s